pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checkout Source Code'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Test'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Docker Build Success'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploy Success'
            }
        }
    }
}
